### ISSUE TITLE
Global is reserved keyword.

### ISSUE THREAD

**Issue by taoso** [krakjoe/inspector#2]
At https://github.com/krakjoe/inspector/blob/master/src/global.c#L61 , the `Global` is not allowed to used as a part of class name.

**Comment by hikari-no-yume** [comment]
Yep. I [worked around this by using a variable class name](https://github.com/TazeTSchnitzel/ElePHPants-Love-Coffee/blob/28718a577c43ec86b0895e18bd00c5c3a8e3327e/src/InspectorOplineGrabber.php#L29): 

``` PHP
$ohMyGodJoeReally = "Inspector\Global";
$function = new $ohMyGodJoeReally($functionName);
```

But this really isn't ideal ^^'

**Comment by krakjoe** [comment]
I just fixed that, changed to Func ...
